version: "3"

services:
  # redis:
  #   image: redis:6-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - my-network

  fastapi:
    build: .
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # depends_on:
    #   - redis
    networks:
      - my-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # celery:
  #   image: celery:4
  #   command: celery -A app.worker worker --loglevel=INFO
  #   depends_on:
  #     - redis
  #   networks:
  #     - my-network
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379

networks:
  my-network:
    driver: bridge
