version: "3"

services:

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: <root password>
      MYSQL_DATABASE: tether_gateway
      MYSQL_USER: <username sql>
      MYSQL_PASSWORD: <username password>
    networks:
      - my-network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  fastapi:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
      - mysql
    networks:
      - my-network
    volumes:
      - logs:/app/logs
    environment:
      SQLALCHEMY_DATABASE_URL: mysql+pymysql://<username>:<password>@mysql/tether_gateway
      CACHE_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0

  withdraw:
    build:
      context: .
      dockerfile: celery_withdraw/Dockerfile
    depends_on:
      - redis
      - mysql
    networks:
      - my-network
    volumes:
      - logs:/withdraw/logs
    environment:
      SQLALCHEMY_DATABASE_URL: mysql+pymysql://<username>:<password>@mysql/tether_gateway
      CACHE_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      
  deposit:
    build:
      context: .
      dockerfile: celery_deposit/Dockerfile
    depends_on:
      - redis
      - mysql
    networks:
      - my-network
    volumes:
      - logs:/deposit/logs
    environment:
      SQLALCHEMY_DATABASE_URL: mysql+pymysql://<username>:<password>@mysql/tether_gateway
      CACHE_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      
  transfer:
    build:
      context: .
      dockerfile: celery_transfer/Dockerfile
    depends_on:
      - redis
      - mysql
    networks:
      - my-network
    volumes:
      - logs:/transfer/logs
    environment:
      SQLALCHEMY_DATABASE_URL: mysql+pymysql://<username>:<password>@mysql/tether_gateway
      CACHE_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      
networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
  logs:
  